#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/open62541/build"

mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

cmake "$SCRIPT_DIR/open62541" \
    -DCMAKE_BUILD_TYPE=Debug \
    -DUA_ARCHITECTURE=posix \
    -DUA_BUILD_UNIT_TESTS=ON \
    -DUA_ENABLE_AUDITING=ON \
    -DUA_ENABLE_DA=ON \
    -DUA_ENABLE_DATATYPES_ALL=ON \
    -DUA_ENABLE_DEBUG_SANITIZER=ON \
    -DUA_ENABLE_DIAGNOSTICS=ON \
    -DUA_ENABLE_DISCOVERY=ON \
    -DUA_ENABLE_DISCOVERY_SEMAPHORE=ON \
    -DUA_ENABLE_ENCRYPTION=OFF \
    -DUA_ENABLE_HISTORIZING=ON \
    -DUA_ENABLE_JSON_ENCODING=ON \
    -DUA_ENABLE_LWS=ON \
    -DUA_ENABLE_SUBSCRIPTIONS_EVENTS=ON \
    -DUA_ENABLE_TYPEDESCRIPTION=ON \
    -DUA_ENABLE_XML_ENCODING=ON \
    -DUA_LOGLEVEL=100 \
    -DUA_MULTITHREADING=100 \
    -DUA_NAMESPACE_ZERO=REDUCED
